### ISSUE TITLE
[SUGESSTION] Vorschläge zu Missionen

### ISSUE THREAD

**Issue by MisterMedion** [Achimobil/FS25_MoreMissions#3]
Hey ich hätte hier einige Vorschläge für die Verbesserung von Missionen:

- Holz-Missionen deaktivieren / Im Einstellungsmenü die verschiedenen Missionstypen aktivieren/deaktivieren.
- Einzelne Missionen aus der Verfügbarkeitsliste löschen ohne sie anzunehmen -> Mission verweigern
- Per Knopfdruck Missonen neu laden -> es werden neue Missionen mit zb. anderen Feldfrüchten generiert
- Pappel-Missionen
- Bonus-System wenn man für den selben Besitzer mehrere Aufträge abschliesst

**Comment by Achimobil** [comment]
Also so was ist in dem Mod nicht geplant. Er ist ja kein better contract oder so sondern einfach nur mehr missionen annehmen können und ende.
