### ISSUE TITLE
Mietgeräte teurer wie der Auftrag Wert hat?

### ISSUE THREAD

**Issue by Martin9569** [Achimobil/FS25_MoreMissions#5]
Mir ist aufgefallen, das teilweise die Leihgeräte teuer sind, oder sogar den Wert des Auftrages übersteigen.
Ist das so gewollt ? Im Anhang habe ich so ein beispiel.
![1](https://github.com/user-attachments/assets/3c9ad14c-63e9-4f23-b62b-7db3f6fd2c75)

**Comment by Achimobil** [comment]
Das musst du an Giants melden, das hat nichts mit dem More Missions mod zu tun.
Mein Mod sorgt nur dafür dass du mehr als 3 Missionen annehmen kannst.
