### ISSUE TITLE
Possible to create a mission limit per farm ?

### ISSUE THREAD

**Issue by Codra11** [Achimobil/FS25_MoreMissions#6]
Good morning,

I'm on a server and in our rules, we want each farm to take a mission and must finish it before taking a new one.
Is it possible to modify a parameter in LUA to limit the number of missions per farm ?

Guten Morgen,

Ich bin auf einem Server und in unseren Regeln wollen wir, dass jede Farm eine Mission annimmt und diese abschließen muss, bevor sie eine neue annimmt.
Ist es möglich, einen Parameter in LUA zu ändern, um die Anzahl der Missionen pro Farm zu begrenzen ?

Thank you so much

**Comment by Achimobil** [comment]
Not with my mod, my mod is  only for having unlimited missions acceptable. 
But Please take a look at this mod: https://www.farming-simulator.com/mod.php?mod_id=304463&title=fs2025
There you can configure a lot in XML, also the maxContractsPerFarm can be set to 1.

**Comment by Codra11** [comment]
Thank you very much for the information.
